version: '3'
services:
  nginx-reverse-proxy:
    build: .
    container_name: docker-proxy
    restart: unless-stopped
    ports:
      - "60000:60000"
      - "60001:60001"
      - "60003:60003"
      - "60004:60004"
    environment:
      - PROXY_PASS_TARGET=192.168.178.33
